Rel constants script
php-fig/link-util pull request #6
Opened 2019-12-08 18:34 UTC by Crell

Replaces #5.

Here's a new version that uses the published IANA link registry to build a complete set of constants.

Bizzarely, IANA has scripts blocked from downloading the XML file.  That is moronic, IMO, but c'est la vie.  I've checked it in here, but the whole thing can be rebuilt by updating that file with wget and rerunning the build script, then committing everything.

2019-12-08 18:50 UTC, evert commented
neat!

2019-12-08 23:29 UTC, dunglas approved these changes
Nice!

2019-12-09 17:21 UTC, weierophinney commented
> Bizzarely, IANA has scripts blocked from downloading the XML file. That is moronic, IMO, but c'est la vie. I've checked it in here, but the whole thing can be rebuilt by updating that file with wget and rerunning the build script, then committing everything.

IIRC, the way we worked around this was to provide a `User-Agent` header with something mimicing a browser user-agent string.

2019-12-09 17:57 UTC, weierophinney requested changes
Two comments:

- You _should_ be able to download the script from the IANA if you pass a `User-Agent` header. I just tried the following: `curl_setopt($handle, CURLOPT_HTTPHEADER, ['User-Agent; php-fig/fig-utils'])` and had success.
- Let's omit the `$note` portion of the generated docblocks if there is no note.

2019-12-09 17:57 UTC, weierophinney commented on rebuild-rels.php
> +     * {$note}
The majority of the entries do not have notes, which means we end up with the majority having structures like this:

```php
/**
  * Refers to...
  *
  *
  *
  * @see iana link
  */
```

In other words, two extra lines for each docblock.

I'm thinking that maybe this should be:

```php
/**
  * {$description}{$note}
  *
  * @see {$seeUri}
  */
```

If a note is detected, then it uses the following format:

```php
private const NOTE_TEMPLATE = <<< 'END'

 * {$note}
 *
END;
```

Yes, a bit more work, but it makes the source more readable in the end.

2019-12-18 15:16 UTC, weierophinney approved these changes
One minor typo, but otherwise looks good. :ship:

2019-12-18 15:16 UTC, weierophinney commented on rebuild-rels.php
> +     *   An itrable of SimpleXml elements from the Link Relations XML file.
```suggestion
     *   An iterable of SimpleXml elements from the Link Relations XML file.
```

2019-12-18 15:40 UTC, merged